# Generated by Django 3.2.8 on 2022-02-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_cnt', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
